version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install -y build-essential cmake qtdeclarative5-dev opencl-headers ocl-icd-opencl-dev
      - run:
          name: Build
          command: mkdir build && 
                   cd build &&
                   cmake .. &&
                   make -j4
  test:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test
      
