version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: apt-get update -qq && apt-get install qtdeclarative5-dev opencl-headers
      - run: mkdir -p build && cd build
  test:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      #- test
      
      
      
#language: cpp

#sudo: required

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - gcc-6
#      - g++-6
#      - cmake
      
#before_script:
# - sudo add-apt-repository --yes ppa:beineri/opt-qt-5.10.1-trusty
# - sudo apt-get update -qq
# - sudo apt-get install qt510base qt510declarative
   
#script:
#  - mkdir build
#  - cd build
#  - source /opt/qt510/bin/qt510-env.sh
#  - cmake .. # -DCMAKE_PREFIX_PATH=/opt/qt
#  - make -j4
#  # removed _after section, otherwise build would not fail if tests fail
#  # reference: https://docs.travis-ci.com/user/customizing-the-build#Breaking-the-Build
#  - cd bin/
#  - chmod +x OCTests
#  - ./OCTests
